/*
 * Copyright (C) 2026 SwiftFloris Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.patrickgold.florisboard.app

import android.app.LocaleManager
import android.content.Context
import android.os.LocaleList
import dev.patrickgold.florisboard.BuildConfig
import org.florisboard.lib.android.AndroidVersion

/**
 * The Settings UI language, and how it relates to Android's per-app language setting.
 *
 * SwiftFloris has always had an in-app picker backed by `prefs.other.settingsLanguage`, which
 * swaps the resource context the Settings tree renders against. On Android 13+ the platform
 * owns the same concept, and the two used to be unaware of each other: the app never appeared
 * under Settings -> Apps -> Language because it declared no `android:localeConfig`, and a
 * per-app language chosen there could be silently overridden by the stored preference at the
 * next launch.
 *
 * The manifest entry is now generated by AGP from the shipped `values-<locale>` resources, and
 * this object keeps the two settings pointing at the same locale: the picker writes through to
 * the platform on API 33+, and the platform's value wins on startup, because a user who changed
 * it in system Settings changed it more recently than whatever the preference remembers.
 */
object AppUiLocale {
    /** The picker value meaning "follow the system language". */
    const val SYSTEM_DEFAULT_TAG = "auto"

    /**
     * BCP-47 tags for every shipped UI translation, generated at build time from the
     * `values-<locale>` resource directories. Sorted, and never containing [SYSTEM_DEFAULT_TAG].
     */
    val shippedTags: List<String> = parseShippedTags(BuildConfig.SHIPPED_UI_LOCALES)

    /**
     * Reads the per-app language Android is holding for this app, as a picker value.
     *
     * Returns [SYSTEM_DEFAULT_TAG] when no per-app language is set, and on Android 12 and
     * below, where the platform has no such concept.
     */
    fun systemAppLocaleTag(context: Context): String {
        if (!AndroidVersion.ATLEAST_API33_T) return SYSTEM_DEFAULT_TAG
        val locales = context.getSystemService(LocaleManager::class.java)
            ?.applicationLocales
            ?: return SYSTEM_DEFAULT_TAG
        return if (locales.isEmpty) SYSTEM_DEFAULT_TAG else locales[0].toLanguageTag()
    }

    /**
     * Pushes a picker value to Android's per-app language setting, so the choice is visible in
     * system Settings and survives outside the app's own resource context.
     *
     * A no-op on Android 12 and below, where `prefs.other.settingsLanguage` plus the
     * configuration context in [FlorisAppActivity] remain the only mechanism.
     */
    fun applySystemAppLocale(context: Context, tag: String) {
        if (!AndroidVersion.ATLEAST_API33_T) return
        val manager = context.getSystemService(LocaleManager::class.java) ?: return
        val requested = if (tag == SYSTEM_DEFAULT_TAG) {
            LocaleList.getEmptyLocaleList()
        } else {
            LocaleList.forLanguageTags(tag)
        }
        // Setting the same value again restarts the activity for nothing.
        if (manager.applicationLocales != requested) {
            manager.applicationLocales = requested
        }
    }

    /**
     * Decides which of the two stored values should win at startup.
     *
     * The platform value wins whenever it disagrees, because it can only have been set through
     * system Settings, which the user reached after the preference was last written. Returns
     * null when nothing needs to change, so the caller does not write the preference on every
     * launch.
     */
    fun reconcileStoredTag(storedTag: String, systemTag: String): String? {
        if (!AndroidVersion.ATLEAST_API33_T) return null
        return systemTag.takeIf { it != storedTag }
    }

    internal fun parseShippedTags(raw: String): List<String> {
        return raw.split(',')
            .map { it.trim() }
            .filter { it.isNotEmpty() && it != SYSTEM_DEFAULT_TAG }
            .distinct()
            .sorted()
    }
}
