/*
 * Copyright (C) 2026 The FlorisBoard Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.patrickgold.florisboard.app

import dev.patrickgold.jetpref.datastore.model.PreferenceData
import dev.patrickgold.jetpref.datastore.model.PreferenceModel
import dev.patrickgold.jetpref.datastore.runtime.PreferenceModelDuplicateKeyException

@Suppress("DEPRECATION")
class FlorisPreferenceModelImpl : FlorisPreferenceModel() {
    override val declaredPreferenceEntries: Map<PreferenceModel.TypedKey, PreferenceData<*>>

    init {
        val entries = listOf(
            clipboard.useInternalClipboard to "clipboard.useInternalClipboard",
            clipboard.syncToFloris to "clipboard.syncToFloris",
            clipboard.syncToSystem to "clipboard.syncToSystem",
            clipboard.suggestionEnabled to "clipboard.suggestionEnabled",
            clipboard.suggestionTimeout to "clipboard.suggestionTimeout",
            clipboard.historyEnabled to "clipboard.historyEnabled",
            clipboard.historyNumGridColumnsPortrait to "clipboard.historyNumGridColumnsPortrait",
            clipboard.historyNumGridColumnsLandscape to "clipboard.historyNumGridColumnsLandscape",
            clipboard.historyAutoCleanOldEnabled to "clipboard.historyAutoCleanOldEnabled",
            clipboard.historyAutoCleanOldAfter to "clipboard.historyAutoCleanOldAfter",
            clipboard.historyAutoCleanSensitiveEnabled to "clipboard.historyAutoCleanSensitiveEnabled",
            clipboard.historyAutoCleanSensitiveAfter to "clipboard.historyAutoCleanSensitiveAfter",
            clipboard.historySizeLimitEnabled to "clipboard.historySizeLimitEnabled",
            clipboard.historySizeLimit to "clipboard.historySizeLimit",
            clipboard.historyHideOnPaste to "clipboard.historyHideOnPaste",
            clipboard.historyHideOnNextTextField to "clipboard.historyHideOnNextTextField",
            clipboard.clearPrimaryClipAffectsHistoryIfUnpinned to "clipboard.clearPrimaryClipAffectsHistoryIfUnpinned",
            clipboard.historySearchEnabled to "clipboard.historySearchEnabled",
            correction.autoCapitalization to "correction.autoCapitalization",
            correction.autoCorrect to "correction.autoCorrect",
            correction.autoCorrectCommitMode to "correction.autoCorrectCommitMode",
            correction.quickPredictionInsert to "correction.quickPredictionInsert",
            correction.autoSpacePunctuation to "correction.autoSpacePunctuation",
            correction.doubleSpacePeriod to "correction.doubleSpacePeriod",
            correction.rememberCapsLockState to "correction.rememberCapsLockState",
            correction.adaptiveTouchModel to "correction.adaptiveTouchModel",
            correction.multilingualSuggestions to "correction.multilingualSuggestions",
            correction.heuristicSmartCompose to "correction.heuristicSmartCompose",
            devtools.enabled to "devtools.enabled",
            devtools.showPrimaryClip to "devtools.showPrimaryClip",
            devtools.showInputStateOverlay to "devtools.showInputStateOverlay",
            devtools.showSpellingOverlay to "devtools.showSpellingOverlay",
            devtools.showInlineAutofillOverlay to "devtools.showInlineAutofillOverlay",
            devtools.showKeyTouchBoundaries to "devtools.showKeyTouchBoundaries",
            devtools.showDragAndDropHelpers to "devtools.showDragAndDropHelpers",
            devtools.showWindowResizeHandleBoundaries to "devtools.showWindowResizeHandleBoundaries",
            dictionary.enableSystemUserDictionary to "dictionary.enableSystemUserDictionary",
            dictionary.enableFlorisUserDictionary to "dictionary.enableFlorisUserDictionary",
            voice.recognitionEnginePreference to "voice.recognitionEnginePreference",
            voice.embeddedModelPreference to "voice.embeddedModelPreference",
            voice.customCommands to "voice.customCommands",
            dictionary.previewPersonalDictionaryImports to "dictionary.previewPersonalDictionaryImports",
            emoji.preferredSkinTone to "emoji.preferredSkinTone",
            emoji.preferredHairStyle to "emoji.preferredHairStyle",
            emoji.historyEnabled to "emoji.historyEnabled",
            emoji.historyData to "emoji.historyData",
            emoji.historyPinnedUpdateStrategy to "emoji.historyPinnedUpdateStrategy",
            emoji.historyPinnedMaxSize to "emoji.historyPinnedMaxSize",
            emoji.historyRecentUpdateStrategy to "emoji.historyRecentUpdateStrategy",
            emoji.historyRecentMaxSize to "emoji.historyRecentMaxSize",
            emoji.suggestionEnabled to "emoji.suggestionEnabled",
            emoji.suggestionType to "emoji.suggestionType",
            emoji.suggestionUpdateHistory to "emoji.suggestionUpdateHistory",
            emoji.suggestionCandidateShowName to "emoji.suggestionCandidateShowName",
            emoji.suggestionQueryMinLength to "emoji.suggestionQueryMinLength",
            emoji.suggestionCandidateMaxCount to "emoji.suggestionCandidateMaxCount",
            gestures.swipeUp to "gestures.swipeUp",
            gestures.swipeDown to "gestures.swipeDown",
            gestures.swipeLeft to "gestures.swipeLeft",
            gestures.swipeRight to "gestures.swipeRight",
            gestures.spaceBarSwipeUp to "gestures.spaceBarSwipeUp",
            gestures.spaceBarSwipeDown to "gestures.spaceBarSwipeDown",
            gestures.spaceBarSwipeLeft to "gestures.spaceBarSwipeLeft",
            gestures.spaceBarSwipeRight to "gestures.spaceBarSwipeRight",
            gestures.spaceBarLongPress to "gestures.spaceBarLongPress",
            gestures.symbolFlickEnabled to "gestures.symbolFlickEnabled",
            gestures.deleteKeySwipeLeft to "gestures.deleteKeySwipeLeft",
            gestures.deleteKeyLongPress to "gestures.deleteKeyLongPress",
            gestures.swipeDistanceThreshold to "gestures.swipeDistanceThreshold",
            gestures.swipeVelocityThreshold to "gestures.swipeVelocityThreshold",
            sticker.userFolderUri to "sticker.userFolderUri",
            glide.enabled to "glide.enabled",
            glide.showTrail to "glide.showTrail",
            glide.trailTheme to "glide.trailTheme",
            glide.trailDuration to "glide.trailDuration",
            glide.showPreview to "glide.showPreview",
            glide.previewRefreshDelay to "glide.previewRefreshDelay",
            glide.immediateBackspaceDeletesWord to "glide.immediateBackspaceDeletesWord",
            glide.sensitivity to "glide.sensitivity",
            glide.flowThroughSpace to "glide.flowThroughSpace",
            glide.enabledEnglish to "glide.enabledEnglish",
            glide.enabledGerman to "glide.enabledGerman",
            glide.enabledSpanish to "glide.enabledSpanish",
            glide.enabledFrench to "glide.enabledFrench",
            glide.enabledItalian to "glide.enabledItalian",
            glide.enabledPortuguese to "glide.enabledPortuguese",
            inputFeedback.audioEnabled to "inputFeedback.audioEnabled",
            inputFeedback.audioActivationMode to "inputFeedback.audioActivationMode",
            inputFeedback.audioVolume to "inputFeedback.audioVolume",
            inputFeedback.audioFeatKeyPress to "inputFeedback.audioFeatKeyPress",
            inputFeedback.audioFeatKeyLongPress to "inputFeedback.audioFeatKeyLongPress",
            inputFeedback.audioFeatKeyRepeatedAction to "inputFeedback.audioFeatKeyRepeatedAction",
            inputFeedback.audioFeatGestureSwipe to "inputFeedback.audioFeatGestureSwipe",
            inputFeedback.audioFeatGestureMovingSwipe to "inputFeedback.audioFeatGestureMovingSwipe",
            inputFeedback.hapticEnabled to "inputFeedback.hapticEnabled",
            inputFeedback.hapticActivationMode to "inputFeedback.hapticActivationMode",
            inputFeedback.hapticVibrationMode to "inputFeedback.hapticVibrationMode",
            inputFeedback.hapticVibrationDuration to "inputFeedback.hapticVibrationDuration",
            inputFeedback.hapticVibrationStrength to "inputFeedback.hapticVibrationStrength",
            inputFeedback.hapticFeatKeyPress to "inputFeedback.hapticFeatKeyPress",
            inputFeedback.hapticFeatKeyLongPress to "inputFeedback.hapticFeatKeyLongPress",
            inputFeedback.hapticFeatKeyRepeatedAction to "inputFeedback.hapticFeatKeyRepeatedAction",
            inputFeedback.hapticFeatGestureSwipe to "inputFeedback.hapticFeatGestureSwipe",
            inputFeedback.hapticFeatGestureMovingSwipe to "inputFeedback.hapticFeatGestureMovingSwipe",
            `internal`.homeIsBetaToolboxCollapsed to "internal.homeIsBetaToolboxCollapsed",
            `internal`.isImeSetUp to "internal.isImeSetUp",
            `internal`.aiFeaturesExplainerSeen to "internal.aiFeaturesExplainerSeen",
            `internal`.firstRunImportHintSeen to "internal.firstRunImportHintSeen",
            `internal`.versionOnInstall to "internal.versionOnInstall",
            `internal`.versionLastUse to "internal.versionLastUse",
            `internal`.versionLastChangelog to "internal.versionLastChangelog",
            `internal`.notificationPermissionState to "internal.notificationPermissionState",
            sync.channelId to "sync.channelId",
            sync.clusterId to "sync.clusterId",
            sync.deviceId to "sync.deviceId",
            sync.pairedDevicesJson to "sync.pairedDevicesJson",
            sync.manualExportTargetUri to "sync.manualExportTargetUri",
            mcp.disabledDaemonPackages to "mcp.disabledDaemonPackages",
            mcp.signingCertPins to "mcp.signingCertPins",
            mcp.disabledTools to "mcp.disabledTools",
            addon.signingCertPins to "addon.signingCertPins",
            keyboard.windowConfig to "keyboard.windowConfig",
            keyboard.numberRow to "keyboard.numberRow",
            keyboard.hintedNumberRowEnabled to "keyboard.hintedNumberRowEnabled",
            keyboard.hintedNumberRowMode to "keyboard.hintedNumberRowMode",
            keyboard.hintedSymbolsEnabled to "keyboard.hintedSymbolsEnabled",
            keyboard.hintedSymbolsMode to "keyboard.hintedSymbolsMode",
            keyboard.bottomRowPresetJson to "keyboard.bottomRowPresetJson",
            keyboard.utilityKeyEnabled to "keyboard.utilityKeyEnabled",
            keyboard.utilityKeyAction to "keyboard.utilityKeyAction",
            keyboard.spaceBarMode to "keyboard.spaceBarMode",
            keyboard.capitalizationBehavior to "keyboard.capitalizationBehavior",
            keyboard.fontSizeMultiplierPortrait to "keyboard.fontSizeMultiplierPortrait",
            keyboard.fontSizeMultiplierLandscape to "keyboard.fontSizeMultiplierLandscape",
            keyboard.keyboardHeightMultiplierPortrait to "keyboard.keyboardHeightMultiplierPortrait",
            keyboard.keyboardHeightMultiplierLandscape to "keyboard.keyboardHeightMultiplierLandscape",
            keyboard.stylusHandwritingEnabled to "keyboard.stylusHandwritingEnabled",
            keyboard.startInFloatingMode to "keyboard.startInFloatingMode",
            keyboard.floatingOnboardingShown to "keyboard.floatingOnboardingShown",
            keyboard.splitKeyboardEnabled to "keyboard.splitKeyboardEnabled",
            keyboard.landscapeInputUiMode to "keyboard.landscapeInputUiMode",
            keyboard.keySpacingVertical to "keyboard.keySpacingVertical",
            keyboard.keySpacingHorizontal to "keyboard.keySpacingHorizontal",
            keyboard.popupEnabled to "keyboard.popupEnabled",
            keyboard.mergeHintPopupsEnabled to "keyboard.mergeHintPopupsEnabled",
            keyboard.longPressDelay to "keyboard.longPressDelay",
            keyboard.spaceBarSwitchesToCharacters to "keyboard.spaceBarSwitchesToCharacters",
            keyboard.autoReturnAfterApostrophe to "keyboard.autoReturnAfterApostrophe",
            keyboard.quoteAutoCloseEnabled to "keyboard.quoteAutoCloseEnabled",
            keyboard.incognitoDisplayMode to "keyboard.incognitoDisplayMode",
            localization.displayLanguageNamesIn to "localization.displayLanguageNamesIn",
            localization.displayKeyboardLabelsInSubtypeLanguage to "localization.displayKeyboardLabelsInSubtypeLanguage",
            localization.rememberSubtypePerAppEnabled to "localization.rememberSubtypePerAppEnabled",
            localization.perAppSubtypeMemory to "localization.perAppSubtypeMemory",
            localization.activeSubtypeId to "localization.activeSubtypeId",
            localization.subtypes to "localization.subtypes",
            privacy.smartComposeConsent to "privacy.smartComposeConsent",
            privacy.translationConsent to "privacy.translationConsent",
            privacy.mcpConsent to "privacy.mcpConsent",
            other.settingsTheme to "other.settingsTheme",
            other.accentColor to "other.accentColor",
            other.settingsLanguage to "other.settingsLanguage",
            other.showAppIcon to "other.showAppIcon",
            physicalKeyboard.showOnScreenKeyboard to "physicalKeyboard.showOnScreenKeyboard",
            smartbar.enabled to "smartbar.enabled",
            smartbar.layout to "smartbar.layout",
            smartbar.actionArrangement to "smartbar.actionArrangement",
            smartbar.perAppProfilesEnabled to "smartbar.perAppProfilesEnabled",
            smartbar.flipToggles to "smartbar.flipToggles",
            smartbar.sharedActionsExpanded to "smartbar.sharedActionsExpanded",
            smartbar.sharedActionsAutoExpandCollapse to "smartbar.sharedActionsAutoExpandCollapse",
            smartbar.sharedActionsExpandWithAnimation to "smartbar.sharedActionsExpandWithAnimation",
            smartbar.extendedActionsExpanded to "smartbar.extendedActionsExpanded",
            smartbar.extendedActionsPlacement to "smartbar.extendedActionsPlacement",
            spelling.languageMode to "spelling.languageMode",
            spelling.useContacts to "spelling.useContacts",
            spelling.useUdmEntries to "spelling.useUdmEntries",
            suggestion.api30InlineSuggestionsEnabled to "suggestion.api30InlineSuggestionsEnabled",
            suggestion.enabled to "suggestion.enabled",
            suggestion.displayMode to "suggestion.displayMode",
            suggestion.blockPossiblyOffensive to "suggestion.blockPossiblyOffensive",
            suggestion.incognitoMode to "suggestion.incognitoMode",
            suggestion.forceIncognitoModeFromDynamic to "suggestion.forceIncognitoModeFromDynamic",
            suggestion.nextWordPrediction to "suggestion.nextWordPrediction",
            theme.mode to "theme.mode",
            theme.dayThemeId to "theme.dayThemeId",
            theme.nightThemeId to "theme.nightThemeId",
            theme.accentColor to "theme.accentColor",
            theme.perAppAccentEnabled to "theme.perAppAccentEnabled",
            theme.perAppAccentDiscoveryHintState to "theme.perAppAccentDiscoveryHintState",
            theme.sunriseTime to "theme.sunriseTime",
            theme.sunsetTime to "theme.sunsetTime",
            theme.editorColorRepresentation to "theme.editorColorRepresentation",
            theme.editorDisplayKbdAfterDialogs to "theme.editorDisplayKbdAfterDialogs",
            theme.editorLevel to "theme.editorLevel",
        )
        val duplicates = entries
            .groupBy { (entry, _) -> entry.key }
            .filter { it.value.size > 1 }
            .mapValues { (_, duplicates) -> duplicates.map { (_, varName) -> varName } }
        if (duplicates.isNotEmpty()) {
            throw PreferenceModelDuplicateKeyException(
                "dev.patrickgold.florisboard.app.FlorisPreferenceModel",
                duplicates,
            )
        }
        declaredPreferenceEntries = entries
            .map { (entry, _) -> entry }
            .associateBy { PreferenceModel.TypedKey(it.type, it.key) }
    }
}
