/*
 * Copyright (C) 2026 SwiftFloris Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.patrickgold.florisboard.ime.mcp

import java.util.concurrent.atomic.AtomicLong

/**
 * ROADMAP §10.5 L7.4 — IME-side `McpClient` facade.
 *
 * The IME's smart-compose and quick-action surfaces talk to bound
 * MCP daemons through this interface.  The real Android implementation
 * holds a `ServiceConnection` per daemon + dispatches
 * [McpToolCallRequest] across the AIDL bind; tests + the NlpManager
 * stub feed in an in-process implementation.  Either way, callers
 * see the same suspend-friendly contract.
 *
 * `suspend` semantics aren't used here directly — Kotlin coroutines
 * aren't part of the contract because the L7.x slices want to stay
 * usable from a JVM unit test without a Robolectric scope. Callers
 * who want suspension wrap [callTool] in `runInterruptible` or
 * `withContext(Dispatchers.IO)` themselves.
 *
 * Correlation IDs are generated by the client side via
 * [nextCorrelationId] so the daemon doesn't have to keep state across
 * calls.
 */
interface McpClient {

    /**
     * Invoke [toolName] with [parameterJson] on the daemon matching
     * [daemonKey] (resolved via [McpDaemonRegistry]). Blocks the
     * caller's thread until the daemon replies or the call times
     * out.
     *
     * Returns a [McpToolCallResponse] with `errorCode = TIMEOUT`
     * when no reply lands within [timeoutMillis]. Returns
     * `TOOL_NOT_FOUND` when the daemon isn't registered or doesn't
     * advertise the named tool. Returns `PAYLOAD_TOO_LARGE` when
     * [parameterJson] exceeds [McpBridgeContract.MAX_PAYLOAD_BYTES].
     */
    fun callTool(
        daemonKey: DaemonKey,
        toolName: String,
        parameterJson: String,
        timeoutMillis: Long = DEFAULT_TIMEOUT_MILLIS,
    ): McpToolCallResponse

    /** Allocate a fresh correlation id. Must be unique per process. */
    fun nextCorrelationId(): String

    companion object {
        const val DEFAULT_TIMEOUT_MILLIS: Long = 30_000L
    }
}

/**
 * Stub implementation used by the NlpManager's smart-compose path
 * before any real daemon is bound, and by unit tests. Always returns
 * `TOOL_NOT_FOUND` so the caller falls through to the local bigram
 * chain.
 */
object NoOpMcpClient : McpClient {

    private val counter = AtomicLong(1L)

    override fun callTool(
        daemonKey: DaemonKey,
        toolName: String,
        parameterJson: String,
        timeoutMillis: Long,
    ): McpToolCallResponse {
        if (parameterJson.length.toLong() > McpBridgeContract.MAX_PAYLOAD_BYTES) {
            return McpToolCallResponse(
                correlationId = nextCorrelationId(),
                toolName = toolName,
                errorMessage = "parameterJson exceeds MAX_PAYLOAD_BYTES",
                errorCode = McpErrorCode.PAYLOAD_TOO_LARGE,
            )
        }
        return McpToolCallResponse(
            correlationId = nextCorrelationId(),
            toolName = toolName,
            errorMessage = "no daemon bound for ${daemonKey.packageName}",
            errorCode = McpErrorCode.TOOL_NOT_FOUND,
        )
    }

    override fun nextCorrelationId(): String = "mcp-noop-${counter.getAndIncrement()}"
}

/**
 * Active [McpClient] registry — mirrors the
 * `SmartComposeRegistry`/`InlineTranslatorRegistry` `setActive`
 * pattern.  Production startup installs a real Android-backed
 * `McpClient` here; tests + NlpManager pre-bind use [NoOpMcpClient].
 */
object McpClientRegistry {

    @Volatile
    private var current: McpClient = NoOpMcpClient

    fun setActive(client: McpClient) {
        current = client
    }

    fun active(): McpClient = current

    internal fun resetForTest() {
        current = NoOpMcpClient
    }
}
