/*
 * Copyright (C) 2026 SwiftFloris Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */

package dev.patrickgold.florisboard.ime.media.emoji

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import java.nio.file.Files
import java.nio.file.Path

class EmojiDataVersionTest : FunSpec({

    test("default version is unknown") {
        val version = EmojiDataVersion()
        version.cldr shouldBe "unknown"
        version.emoji shouldBe "unknown"
    }

    test("version can be constructed with explicit values") {
        val version = EmojiDataVersion(cldr = "48", emoji = "16.0")
        version.cldr shouldBe "48"
        version.emoji shouldBe "16.0"
    }

    test("empty EmojiData has unknown version") {
        val data = EmojiData.empty()
        data.version.cldr shouldBe "unknown"
        data.version.emoji shouldBe "unknown"
    }

    test("Emoji 17 dry-run fixture parses without updating bundled assets") {
        val distortedFace = String(intArrayOf(0x1FAEA), 0, 1)

        val data = EmojiData.parseEmojiDataLines(
            sequenceOf(
                "# Auto-generated by emoji-test dry-run fixture",
                "# CLDR-VERSION: dry-run",
                "# EMOJI-VERSION: 17.0",
                "",
                "[smileys_emotion]",
                "$distortedFace;distorted face;confused|distorted|E17.0",
            ),
        )

        data.version.cldr shouldBe "dry-run"
        data.version.emoji shouldBe "17.0"

        val emojiSet = data.byCategory[EmojiCategory.SMILEYS_EMOTION]!!.single()
        val emoji = emojiSet.emojis.single()
        emoji.value shouldBe distortedFace
        emoji.name shouldBe "distorted face"
        emoji.keywords shouldBe listOf("confused", "distorted", "E17.0")

        data.bySkinTone[EmojiSkinTone.DEFAULT]!!.single().value shouldBe distortedFace
        data.bySkinTone[EmojiSkinTone.LIGHT_SKIN_TONE]!!.single().value shouldBe distortedFace
    }

    test("bundled root emoji asset stays pinned to CLDR 48 and Emoji 16") {
        val rootAsset = mainAssetText("ime/media/emoji/root.txt")

        rootAsset shouldContain "# CLDR-VERSION: 48"
        rootAsset shouldContain "# EMOJI-VERSION: 16.0"
        rootAsset shouldNotContain "# EMOJI-VERSION: 17.0"
    }
})

private fun mainAssetText(relativePath: String): String {
    val candidates = listOf(
        Path.of("src", "main", "assets").resolve(relativePath),
        Path.of("app", "src", "main", "assets").resolve(relativePath),
    )
    val path = candidates.firstOrNull { Files.exists(it) }
        ?: error("Cannot find main asset $relativePath from ${Path.of("").toAbsolutePath()}")
    return Files.readString(path)
}
