/*
 * Copyright (C) 2026 SwiftFloris Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */

package dev.patrickgold.florisboard.ime.media.emoji

import io.kotest.assertions.withClue
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import java.nio.file.Files
import java.nio.file.Path

class EmojiDataVersionTest : FunSpec({

    test("default version is unknown") {
        val version = EmojiDataVersion()
        version.cldr shouldBe "unknown"
        version.emoji shouldBe "unknown"
    }

    test("version can be constructed with explicit values") {
        val version = EmojiDataVersion(cldr = "48", emoji = "16.0")
        version.cldr shouldBe "48"
        version.emoji shouldBe "16.0"
    }

    test("version matching is strict for both metadata sources") {
        val expected = EmojiDataVersion(cldr = "48", emoji = "17.0")

        expected.matches(expected) shouldBe true
        expected.matches(expected.copy(emoji = "16.0")) shouldBe false
        expected.matches(expected.copy(cldr = "48.2")) shouldBe false
    }

    test("empty EmojiData has unknown version") {
        val data = EmojiData.empty()
        data.version.cldr shouldBe "unknown"
        data.version.emoji shouldBe "unknown"
    }

    test("Emoji 17 dry-run fixture parses without updating bundled assets") {
        val distortedFace = String(intArrayOf(0x1FAEA), 0, 1)

        val data = EmojiData.parseEmojiDataLines(
            sequenceOf(
                "# Auto-generated by emoji-test dry-run fixture",
                "# CLDR-VERSION: dry-run",
                "# EMOJI-VERSION: 17.0",
                "",
                "[smileys_emotion]",
                "$distortedFace;distorted face;confused|distorted|E17.0",
            ),
        )

        data.version.cldr shouldBe "dry-run"
        data.version.emoji shouldBe "17.0"

        val emojiSet = data.byCategory[EmojiCategory.SMILEYS_EMOTION]!!.single()
        val emoji = emojiSet.emojis.single()
        emoji.value shouldBe distortedFace
        emoji.name shouldBe "distorted face"
        emoji.keywords shouldBe listOf("confused", "distorted", "E17.0")

        data.bySkinTone[EmojiSkinTone.DEFAULT]!!.single().value shouldBe distortedFace
        data.bySkinTone[EmojiSkinTone.LIGHT_SKIN_TONE]!!.single().value shouldBe distortedFace
    }

    // CLDR 48 (2025-10-29) is the Unicode 17 update: "Updated for Unicode 17,
    // including new names and search terms for new emoji, new sort-order."
    // The bundled assets were generated from it, so they have carried the
    // Emoji 17.0 characters all along while the header still declared 16.0.
    // These cases check the declared version against what is actually in the
    // file, in both directions, so the label cannot drift again.
    val emoji17BaseCodePoints = mapOf(
        "distorted face" to 0x1FAEA,
        "fight cloud" to 0x1FAEF,
        "hairy creature" to 0x1FAC8,
        "orca" to 0x1FACD,
        "landslide" to 0x1F6D8,
        "trombone" to 0x1FA8A,
        "treasure chest" to 0x1FA8E,
    )
    val bundledAssets = listOf("root", "de", "en", "es", "fr", "it", "pt")

    test("every bundled emoji asset declares the CLDR and Emoji version it was built from") {
        for (locale in bundledAssets) {
            val asset = mainAssetText("ime/media/emoji/$locale.txt")

            withClue("$locale.txt") {
                asset shouldContain "# CLDR-VERSION: ${EmojiData.BundledVersion.cldr}"
                asset shouldContain "# EMOJI-VERSION: ${EmojiData.BundledVersion.emoji}"
                asset shouldNotContain "# EMOJI-VERSION: 16.0"
            }
        }
    }

    test("bundled assets actually contain every Emoji 17.0 base character they claim") {
        for (locale in bundledAssets) {
            val asset = mainAssetText("ime/media/emoji/$locale.txt")

            for ((name, codePoint) in emoji17BaseCodePoints) {
                val character = String(intArrayOf(codePoint), 0, 1)
                withClue("$locale.txt is missing $name (U+${codePoint.toString(16).uppercase()})") {
                    asset shouldContain character
                }
            }
        }
    }
})

private fun mainAssetText(relativePath: String): String {
    val candidates = listOf(
        Path.of("src", "main", "assets").resolve(relativePath),
        Path.of("app", "src", "main", "assets").resolve(relativePath),
    )
    val path = candidates.firstOrNull { Files.exists(it) }
        ?: error("Cannot find main asset $relativePath from ${Path.of("").toAbsolutePath()}")
    return Files.readString(path)
}
